[workspace]
resolver = "2"
members = ["iced_anim", "iced_anim_derive", "examples"]

[workspace.dependencies]
iced = { git = "https://github.com/iced-rs/iced", rev = "169667ef1b4fa754ed1edb5fa0e845aede2638fb", features = ["advanced"] }
